Repository bleehu/Compound_X, pull requests merged in 2018-02, with the labels that each got.

#330 Borderline-obnoxiously nitpicky style fixes
  CharacterCreation/04_01_Melee_&_Thrown_Weapons.txt
Labels: Greenlit - Awaiting Review

#307 stylized melee weapons to make it easy to read to update Pigeon's cha…
  CharacterCreation/04_01_Melee_&_Thrown_Weapons.txt
Labels: Greenlit - Awaiting Review

#313 Mh c2 engineer
  CharacterCreation/Class-Specific Documentation/Engineer Processes.txt
Labels: Greenlit - Awaiting Review, Priority - High

#314 Mh c2 engineer
  01_01_Basic_Rules.txt
  CharacterCreation/04_02_Pistols.txt
  CharacterCreation/04_03_SMGs_&_Shotguns.txt
  CharacterCreation/04_06_MachineGuns_HeavyWeps_&_RocketLaunchers.txt
  CharacterCreation/Class-Specific Documentation/Engineer Processes.txt
Labels: Greenlit - Awaiting Review, Priority - Med

#327 Mh issue 316 disrupted
  01_02_Conditions.txt
  CharacterCreation/Class-Specific Documentation/Doctor Procedures.txt
Labels: Greenlit - Awaiting Review

#333 added Defuse and Jam DC to the Engineer's IED process
  CharacterCreation/Class-Specific Documentation/Engineer Processes.txt
Labels: Greenlit - Awaiting Review, Priority - Med
