Repository bleehu/Compound_X, pull requests merged in 2018-03, with the labels that each got.

#347 Polish up Regression Override
  CharacterCreation/Class-Specific Documentation/Engineer Processes.txt
Labels: Greenlit - Awaiting Review

#346 added needle cost to Doctor Proceedure: Mild Stim
  CharacterCreation/Class-Specific Documentation/Doctor Procedures.txt
Labels: Greenlit - Awaiting Review

#305 Mh version beta 0.0.3
  01_01_Basic_Rules.txt
  01_02_Conditions.txt
  01_03_Skill_DCs.txt
  02_01_Advanced_Movement:_Microgravity.txt
  03_Glossary_of_Terms.txt
  Basic Rules.txt
  C_X_CharacterSheet_Printable - Character Sheet.pdf
  CharacterCreation/00_New_Player_Walkthrough.txt
  CharacterCreation/01_Races.txt
  CharacterCreation/02_Classes.txt
  CharacterCreation/04_02_Pistols.txt
  CharacterCreation/04_03_SMGs_&_Shotguns.txt
  CharacterCreation/04_06_MachineGuns_HeavyWeps_&_RocketLaunchers.txt
  CharacterCreation/05_ArmourList.txt
  CharacterCreation/07_Items.txt
  CharacterCreation/Class-Specific Documentation/Doctor Procedure Tree - Hippocratic.png
  CharacterCreation/Class-Specific Documentation/Doctor Procedure Tree - Malpractice.png
  CharacterCreation/Class-Specific Documentation/Doctor Procedures.txt
  CharacterCreation/Class-Specific Documentation/Engineer Process Tree - Build.png
  CharacterCreation/Class-Specific Documentation/Engineer Process Tree - Repair.png
  CharacterCreation/Class-Specific Documentation/Engineer Processes.txt
  CharacterCreation/Class-Specific Documentation/Medic Proceedures.txt
  CharacterCreation/Class-Specific Documentation/Medic Skill Tree - Malpractice.png
  README.md
Labels: Greenlit - Awaiting Review, Priority - High

#329 bumped version number to 0.0.4
  README.md
Labels: Greenlit - Awaiting Review, Priority - High

#355 bumped version number to 0.0.5
  README.md
Labels: Greenlit - Awaiting Review, Priority - High

#354 Mh version beta 0.0.5
  01_02_Conditions.txt
  CharacterCreation/04_01_Melee_&_Thrown_Weapons.txt
  CharacterCreation/Class-Specific Documentation/Doctor Procedures.txt
  CharacterCreation/Class-Specific Documentation/Engineer Processes.txt
  README.md
Labels: Greenlit - Awaiting Review, Priority - High

#360 MH fishing pole
  CharacterCreation/07_Items.txt
Labels: Greenlit - Awaiting Review

#359 buffed Refractory Spray
  CharacterCreation/Class-Specific Documentation/Engineer Processes.txt
Labels: Greenlit - Awaiting Review

#358 Mh issue 353 engi dmg type
  01_01_Basic_Rules.txt
  CharacterCreation/Class-Specific Documentation/Engineer Processes.txt
Labels: Greenlit - Awaiting Review

#334 Clarified some language in melee stats in Engineering Processes
  CharacterCreation/Class-Specific Documentation/Engineer Processes.txt
Labels: Greenlit - Awaiting Review, Priority - Med

#378 added hacking DC to ASPRO-S
  CharacterCreation/Class-Specific Documentation/Engineer Processes.txt
Labels: Greenlit - Awaiting Review, Priority - Low

#380 added 2 slot requirement for large munitions
  CharacterCreation/04_06_MachineGuns_HeavyWeps_&_RocketLaunchers.txt
Labels: Greenlit - Awaiting Review, Gripe, Priority - High

#388 added detailed description of IO Ports as per Issue #351
  CharacterCreation/Class-Specific Documentation/Engineer Processes.txt
Labels: Greenlit - Awaiting Review, Priority - Med

#387 Stylize Humans
  CharacterCreation/01_01_Races_Human
Labels: Greenlit - Awaiting Review

#389 Mh version b 0.0.6
  01_01_Basic_Rules.txt
  CharacterCreation/07_Items.txt
  CharacterCreation/Class-Specific Documentation/Engineer Processes.txt
  README.md
Labels: Greenlit - Awaiting Review, Priority - High

#391 Mh issue 352 cerbe turret
  03_Glossary_of_Terms.txt
  CharacterCreation/Class-Specific Documentation/Engineer Processes.txt
Labels: Greenlit - Awaiting Review, Priority - Med

#390 added IO ports to glossary and added actual definition of IO in IO Ports
  03_Glossary_of_Terms.txt
  CharacterCreation/Class-Specific Documentation/Engineer Processes.txt
Labels: Greenlit - Awaiting Review, Priority - Low

#326 changed the penalty for having 1 Charisma
  01_01_Basic_Rules.txt
  01_02_Conditions.txt
  03_Glossary_of_Terms.txt
Labels: Greenlit - Awaiting Review, Priority - Med

#392 Added Awareness to Basic Rules
  01_01_Basic_Rules.txt
Labels: Greenlit - Awaiting Review

#395 Mh issue 130 baffled ammo
  CharacterCreation/04_00_WeaponAttachments.txt
Labels: Greenlit - Awaiting Update, Priority - Med

#396 added shredder rounds
  CharacterCreation/04_00_WeaponAttachments.txt
Labels: Greenlit - Awaiting Review, Priority - Med

#401 added Short Circuit rounds
  CharacterCreation/04_00_WeaponAttachments.txt
Labels: Greenlit - Awaiting Review, Priority - Med

#402 Update README.md
  README.md
Labels: Greenlit - Awaiting Review, Priority - Low

#403 Universal Translator Item
  CharacterCreation/07_Items.txt
Labels: Greenlit - Awaiting Review, Priority - Low

#404 Update Critical Example
  01_01_Basic_Rules.txt
Labels: Greenlit - Awaiting Review, Priority - Low

#409 Replaced old Engineering trees with new ones.
  CharacterCreation/Class-Specific Documentation/Engineer Process Tree - Build.png
  CharacterCreation/Class-Specific Documentation/Engineer Process Tree - Repair.png
Labels: Greenlit - Awaiting Review, Gripe, Priority - High

#406 added Flamethrower peripheral
  CharacterCreation/Class-Specific Documentation/Engineer Processes.txt
Labels: Greenlit - Awaiting Review, Priority - Low
