Repository bleehu/Compound_X, pull requests merged in 2018-04, with the labels that each got.

#407 Stylize long rifles
  CharacterCreation/04_05_Long_Rifles_&_DMRs.txt
Labels: Greenlit - Awaiting Review, Priority - Med

#408 stylized carbines
  CharacterCreation/04_04_Carbines_AssaultRifles_&_BattleRifles.txt
Labels: Greenlit - Awaiting Review, Priority - Med

#394 added gluon rounds
  CharacterCreation/04_00_WeaponAttachments.txt
Labels: Greenlit - Awaiting Review, Priority - Med

#379 added Juggler Feat
  CharacterCreation/03_Feats.txt
Labels: Greenlit - Awaiting Review, Priority - Low

#418 buffed gluon rounds 'cause they're pricey
  CharacterCreation/04_00_WeaponAttachments.txt
Labels: Greenlit - Awaiting Review, Priority - Low

#419 changed the style of feats
  CharacterCreation/03_Feats.txt
Labels: Greenlit - Awaiting Review

#393 added Vorpal Rounds
  CharacterCreation/04_00_WeaponAttachments.txt
Labels: Greenlit - Awaiting Review, Priority - Med

#422 Changed the style of weapon attachments.
  CharacterCreation/04_00_WeaponAttachments.txt
Labels: Greenlit - Awaiting Review, Priority - High

#423 added missing burst fire rates
  CharacterCreation/04_04_Carbines_AssaultRifles_&_BattleRifles.txt
Labels: Greenlit - Awaiting Review, Gripe, Priority - Med

#424 removed reference to Medicine Saving Throws
  01_01_Basic_Rules.txt
Labels: Greenlit - Awaiting Review, Gripe, Priority - Med

#421 Mh issue 130 lv10 ammo
  CharacterCreation/04_00_WeaponAttachments.txt
Labels: Greenlit - Awaiting Review, Priority - Med

#426 Mh issue 349 cs burn
  CharacterCreation/Class-Specific Documentation/Doctor Procedures.txt
  CharacterCreation/Class-Specific Documentation/Engineer Processes.txt
Labels: Greenlit - Awaiting Review, Priority - Med

#427 Buffed Ceramic Catalyst.
  CharacterCreation/Class-Specific Documentation/Engineer Processes.txt
Labels: Greenlit - Awaiting Review, Priority - Low

#432 Skills consistency pass
  01_01_Basic_Rules.txt
Labels: Bug

#447 bumped version number to 0.0.8
  README.md
Labels: Greenlit - Awaiting Review, Priority - Low

#417 Mh version b 0.0.7 -> RC
  01_01_Basic_Rules.txt
  01_02_Conditions.txt
  03_Glossary_of_Terms.txt
  CharacterCreation/00_New_Player_Walkthrough.txt
  CharacterCreation/01_Species.txt
  CharacterCreation/06_01_Systemized_Skills.txt
  CharacterCreation/07_Items.txt
  CharacterCreation/Class-Specific Documentation/Engineer Process Tree - Build.png
  CharacterCreation/Class-Specific Documentation/Engineer Process Tree - Repair.png
  CharacterCreation/Class-Specific Documentation/Engineer Processes.txt
  README.md
Labels: Greenlit - Awaiting Review, Priority - High

#450 Turtlelord26 fix dev commit trash
  CharacterCreation/02_Classes.txt
  CharacterCreation/03_Feats.txt
  CharacterCreation/04_01_Melee_&_Thrown_Weapons.txt
Labels: Greenlit - Awaiting Review

#449 Melee 2.1 Nonlethal Damage Update
  01_01_Basic_Rules.txt
Labels: Greenlit - Awaiting Review

#441 Turtlelord26 Melee 2.1 Unarmed Combat Experience Levels
  CharacterCreation/02_Classes.txt
  CharacterCreation/03_Feats.txt
  CharacterCreation/04_01_Melee_&_Thrown_Weapons.txt
Labels: Greenlit - Awaiting Review

#462 Delete old skills doc
  CharacterCreation/06_01_Systemized_Skills.txt
  CharacterCreation/06_Skills.txt
Labels: Greenlit - Awaiting Review

#463 Mh/partial play update
  Basic Rules.txt
  CharacterCreation/02_Classes.txt
  CharacterCreation/03_Feats.txt
  CharacterCreation/04_00_WeaponAttachments.txt
  CharacterCreation/04_01_Melee_&_Thrown_Weapons.txt
  CharacterCreation/04_01_Weapons.txt
  CharacterCreation/04_02_Pistols.txt
  CharacterCreation/04_02_WeaponAttachments.txt
  CharacterCreation/04_03_Advanced Weapons.txt
  CharacterCreation/04_03_SMGs_&_Shotguns.txt
  CharacterCreation/04_04_Carbines_AssaultRifles_&_BattleRifles.txt
  CharacterCreation/04_05_Long_Rifles_&_DMRs.txt
  CharacterCreation/04_06_MachineGuns_HeavyWeps_&_RocketLaunchers.txt
  CharacterCreation/05_ArmourList.txt
  CharacterCreation/06_Skills.txt
  CharacterCreation/Class-Specific Documentation/Medic Proceedures.txt
  CharacterCreation/Class-Specific Documentation/Medic Skill Tree - Malpractice.png
  CharacterCreation/Class-Specific Documentation/Tome of Spells.txt
  Glossary_of_Terms.txt
Labels: Greenlit - Awaiting Review, Priority - High

#467 Mh/mass version 0.1.0
  01_01_Basic_Rules.txt
  CharacterCreation/02_Classes.txt
  CharacterCreation/03_Feats.txt
  CharacterCreation/04_00_WeaponAttachments.txt
  CharacterCreation/04_01_Melee_&_Thrown_Weapons.txt
  CharacterCreation/04_04_Carbines_AssaultRifles_&_BattleRifles.txt
  CharacterCreation/04_05_Long_Rifles_&_DMRs.txt
  CharacterCreation/04_06_MachineGuns_HeavyWeps_&_RocketLaunchers.txt
  CharacterCreation/06_01_Systemized_Skills.txt
  CharacterCreation/06_Skills.txt
  CharacterCreation/Class-Specific Documentation/Doctor Procedures.txt
  CharacterCreation/Class-Specific Documentation/Engineer Processes.txt
  README.md
Labels: Greenlit - Awaiting Review

#469 Knowledge - General nerf
  CharacterCreation/06_Skills.txt
Labels: Greenlit - Awaiting Review

#470 Turtlelord26 Melee 2.1 Maneuvers
  01_01_Basic_Rules.txt
Labels: Greenlit - Awaiting Review

#472 added flavor text instead of dev note to gunslinger class
  CharacterCreation/02_Classes.txt
Labels: Greenlit - Awaiting Review, Priority - Med

#476 Rearranged the way we store files in our repository.
  Items/04_00_WeaponAttachments.txt
  Items/04_01_Melee_&_Thrown_Weapons.txt
  Items/04_02_Pistols.txt
  Items/04_03_SMGs_&_Shotguns.txt
  Items/04_04_Carbines_AssaultRifles_&_BattleRifles.txt
  Items/04_05_Long_Rifles_&_DMRs.txt
  Items/04_06_MachineGuns_HeavyWeps_&_RocketLaunchers.txt
  Items/05_Armors.txt
  Items/07_Items.txt
Labels: Greenlit - Awaiting Review, Priority - High

#480 Mh/version/0.1.1
  CharacterCreation/02_Classes.txt
  CharacterCreation/03_Feats.txt
  CharacterCreation/06_Skills.txt
  Items/04_00_WeaponAttachments.txt
  Items/04_01_Melee_&_Thrown_Weapons.txt
  Items/04_02_Pistols.txt
  Items/04_03_SMGs_&_Shotguns.txt
  Items/04_04_Carbines_AssaultRifles_&_BattleRifles.txt
  Items/04_05_Long_Rifles_&_DMRs.txt
  Items/04_06_MachineGuns_HeavyWeps_&_RocketLaunchers.txt
  Items/05_Armors.txt
  Items/07_Items.txt
  README.md
Labels: Greenlit - Awaiting Review, Priority - High

#483 Broke up Basic Rules into five documents
  01_01_Basic_Rules.txt
  01_02_Damage_Types_and_Armor_Types.txt
  01_03_Conditions.txt
  01_04_Leveling_Up.txt
  01_05_Cloaking_Rules.txt
Labels: Greenlit - Awaiting Review, Priority - Med

#475 Remove skill from crit range in reloading
  01_01_Basic_Rules.txt
Labels: Greenlit - Awaiting Review

#484 Separated Combat Rules from Basic rules
  01_01_Basic_Rules.txt
  01_02_Combat_Rules.txt
  01_04_Damage_Types_and_Armor_Types.txt
  01_05_Conditions.txt
  01_06_Leveling_Up.txt
  01_07_Cloaking_Rules.txt
Labels: Greenlit - Awaiting Update, Priority - High

#482 added some rules about attack dogs
  CharacterCreation/02_Classes.txt
Labels: Greenlit - Awaiting Review, Priority - Low
