Repository bleehu/Compound_X, pull requests merged in 2018-06, with the labels that each got.

#515 added new feat: kip up
  CharacterCreation/03_Feats.txt
Labels: Greenlit - Awaiting Review

#513 90% of Melee 2.1
  01_02_Combat_Rules.txt
  01_04_Damage_Types_and_Armor_Types.txt
  Items/04_01_Melee_&_Thrown_Weapons.txt
Labels: Greenlit - Awaiting Review

#524 changed glossary terms from sections to sub-headers
  03_Glossary_of_Terms.txt
Labels: Greenlit - Awaiting Review

#521 Remove "crit" from feats list
  CharacterCreation/03_Feats.txt
Labels: Greenlit - Awaiting Review

#495 Mh/version beta 0.1.2/rc
  01_01_Basic_Rules.txt
  01_02_Combat_Rules.txt
  01_04_Damage_Types_and_Armor_Types.txt
  01_05_Conditions.txt
  01_06_Leveling_Up.txt
  01_07_Cloaking_Rules.txt
  CharacterCreation/02_Classes.txt
  CharacterCreation/03_Feats.txt
  Items/04_01_Melee_&_Thrown_Weapons.txt
  README.md
Labels: Greenlit - Awaiting Review, Priority - High

#525 added "return to sender" feat
  CharacterCreation/03_Feats.txt
Labels: Yellowlit - Awaiting Approval

#528 Mh/races push/refract
  CharacterCreation/01_02_Species_ECSC_Security_Drone.txt
  CharacterCreation/01_02_Species_ECSC_Secutiry_Drone
Labels: Yellowlit - Awaiting Approval

#527 Security Drone first pass
  CharacterCreation/01_02_Species_ECSC_Security_Drone.txt
  CharacterCreation/01_02_Species_ECSC_Secutiry_Drone
Labels: Greenlit - Awaiting Review

#526 added overcharged ammo type for lasers
  Items/04_00_WeaponAttachments.txt
Labels: Greenlit - Awaiting Review

#531 Rework Heavy Weapons Expertise
  CharacterCreation/03_Feats.txt
Labels: Greenlit - Awaiting Review

#530 Rework Long Rifle Expertise
  CharacterCreation/03_Feats.txt
Labels: Greenlit - Awaiting Review

#535 Reintroduce Extra-crits
  01_02_Combat_Rules.txt
Labels: Greenlit - Awaiting Review

#534 Add Opaleite Water Visors
  Items/07_Items.txt
Labels: Greenlit - Awaiting Review

#536 replaced the old character readme
  CharacterCreation/README.txt
  CharacterCreation/Readme.md
Labels: Greenlit - Awaiting Review

#533 removed crit from doc proceedures and vorpal rounds.
  CharacterCreation/Class-Specific Documentation/Doctor Procedures.txt
  Items/04_00_WeaponAttachments.txt
Labels: Greenlit - Awaiting Review

#532 Rework Explosives Expertise
  CharacterCreation/03_Feats.txt
Labels: Greenlit - Awaiting Update

#541 Moved a bunch of rules from throwing weapons
  01_02_Combat_Rules.txt
  Items/04_01_Melee_&_Thrown_Weapons.txt
Labels: Greenlit - Awaiting Review

#523 Added Reflex Save to grenades
  Items/04_01_Melee_&_Thrown_Weapons.txt
Labels: Greenlit - Awaiting Review

#543 Moved armor rules to rules doc
  01_02_Combat_Rules.txt
  Items/05_Armors.txt
Labels: Greenlit - Awaiting Review

#548 added IR as a trait for Security Drones
  CharacterCreation/01_02_Species_ECSC_Security_Drone.txt
Labels: Greenlit - Awaiting Review

#544 added section on Security Drone names
  CharacterCreation/01_02_Species_ECSC_Security_Drone.txt
Labels: Greenlit - Awaiting Review

#549 added the Series ten Cinder Drone
  CharacterCreation/01_02_Species_ECSC_Security_Drone.txt
Labels: Greenlit - Awaiting Review

#550 added Series Eleven Cryo Drones
  CharacterCreation/01_02_Species_ECSC_Security_Drone.txt
Labels: Greenlit - Awaiting Review

#556 Clarity update to minimum miss chances
  01_02_Combat_Rules.txt
Labels: Greenlit - Awaiting Review, Gripe, Priority - Med

#552 Adding New Miscellaneous Items
  Items/07_Items.txt
Labels: Greenlit - Awaiting Review, Priority - Low

#568 Turtlelord26 #557 cmb stat table >cmb rules
  01_01_Basic_Rules.txt
  01_02_Combat_Rules.txt
Labels: Greenlit - Awaiting Review

#569 Update Mechanic: Hitting what you intend
  01_02_Combat_Rules.txt
Labels: Greenlit - Awaiting Review

#542 Reworked Weapon Expertise Feats
  CharacterCreation/03_Feats.txt
Labels: Greenlit - Awaiting Review

#571 Turtlelord26 reactions and initiative
  01_02_Combat_Rules.txt
Labels: Greenlit - Awaiting Review

#545 Play -> version 0.1.3
  01_01_Basic_Rules.txt
  01_02_Combat_Rules.txt
  01_04_Damage_Types_and_Armor_Types.txt
  01_05_Conditions.txt
  01_06_Leveling_Up.txt
  01_07_Cloaking_Rules.txt
  03_Glossary_of_Terms.txt
  CharacterCreation/01_Species.txt
  CharacterCreation/02_Classes.txt
  CharacterCreation/03_Feats.txt
  CharacterCreation/04_00_WeaponAttachments.txt
  CharacterCreation/04_01_Melee_&_Thrown_Weapons.txt
  CharacterCreation/04_05_Long_Rifles_&_DMRs.txt
  CharacterCreation/06_01_Systemized_Skills.txt
  CharacterCreation/06_Skills.txt
  CharacterCreation/Class-Specific Documentation/Doctor Procedures.txt
  CharacterCreation/Class-Specific Documentation/Engineer Process Tree - Build.png
  CharacterCreation/Class-Specific Documentation/Engineer Process Tree - Repair.png
  CharacterCreation/Class-Specific Documentation/Engineer Processes.txt
  CharacterCreation/Class-Specific Documentation/Tome of Spells.txt
  Items/04_00_WeaponAttachments.txt
  Items/04_01_Melee_&_Thrown_Weapons.txt
  Items/04_02_Pistols.txt
  Items/04_03_SMGs_&_Shotguns.txt
  Items/04_04_Carbines_AssaultRifles_&_BattleRifles.txt
  Items/04_05_Long_Rifles_&_DMRs.txt
  Items/04_06_MachineGuns_HeavyWeps_&_RocketLaunchers.txt
  Items/05_Armors.txt
  Items/07_Items.txt
  README.md
Labels: Greenlit - Awaiting Review

#583 Mh/hunter dog/dog stats
  CharacterCreation/02_Classes.txt
  CharacterCreation/Class-Specific Documentation/Hunters_Dog.txt
Labels: Greenlit - Awaiting Review, Priority - Low

#584 added dog food item
  Items/07_Items.txt
Labels: Greenlit - Awaiting Review

#582 minor spell checking in the security drone and opaleite pages
  CharacterCreation/01_02_Species_ECSC_Security_Drone.txt
  CharacterCreation/01_04_Species_Opaleites
Labels: Greenlit - Awaiting Review
