Repository bleehu/Compound_X, pull requests merged in 2018-08, with the labels that each got.

#617 Mh/hunter dog/matador
  CharacterCreation/02_Classes.txt
Labels: Greenlit - Awaiting Review

#627 Updated "miss chance", to "Accuracy"
  CharacterCreation/03_Feats.txt
Labels: Greenlit - Awaiting Review, Gripe, Priority - Low

#632 rearranged damage types and armor to surface fall damage rule, did so…
  01_04_Damage_Types_and_Armor_Types.txt
Labels: Greenlit - Awaiting Review

#624 0x0c Constructor Drone
  CharacterCreation/01_02_Species_ECSC_Security_Drone.txt
Labels: Greenlit - Awaiting Update

#633 stylized and re-ordered skills document
  CharacterCreation/06_Skills.txt
Labels: Greenlit - Awaiting Pull Request

#636 Turtlelord26 Nanite Removal: Cloak Rules Update
  01_07_Cloaking_Rules.txt
  Items/05_Armors.txt
Labels: Greenlit - Awaiting Review

#637 Turtlelord26 Hard Point Equipment to Own File
  Items/05_01_Hard_Point_Equipment.txt
  Items/05_Armors.txt
Labels: Greenlit - Awaiting Review

#639 clarified when overcharge ammo jams
  Items/04_00_WeaponAttachments.txt
Labels: Greenlit - Awaiting Review

#640 added new Duck Bob and Weave feat
  CharacterCreation/03_Feats.txt
Labels: Greenlit - Awaiting Review

#641 At long last, Fire Extingushers
  Items/07_Items.txt
Labels: Greenlit - Awaiting Review

#642 Rework Heavy Weapon Expertise 36 Pt Bonus
  CharacterCreation/03_Feats.txt
Labels: Greenlit - Awaiting Review

#630 Turtlelord26 melee weapon damage patch
  01_02_Combat_Rules.txt
  Items/04_01_Melee_&_Thrown_Weapons.txt
Labels: Greenlit - Awaiting Review

#647 Clarify Suppression attacks wording
  01_02_Combat_Rules.txt
Labels: Gripe

#638 De-duplicated and re-arranged basic rules
  01_01_Basic_Rules.txt
  03_Glossary_of_Terms.txt
  CharacterCreation/03_Feats.txt
Labels: Greenlit - Awaiting Review

#644 Mh/play playable/attachments pass
  01_01_Basic_Rules.txt
  Items/04_00_WeaponAttachments.txt
Labels: Greenlit - Awaiting Review

#650 Version bump to 0.1.6
  README.md
Labels: Greenlit - Awaiting Review

#652 VAE Combat Sword Typo
  Items/04_01_Melee_&_Thrown_Weapons.txt
Labels: Greenlit - Awaiting Review

#615 Mh/hunter dog/superbranch
  CharacterCreation/02_Classes.txt
  CharacterCreation/Class-Specific Documentation/Hunters_Dog.txt
  Items/07_Items.txt
Labels: Greenlit - Awaiting Review

#654 Turtlelord26 Reflavored Engineer Energy into Potential
  CharacterCreation/02_Classes.txt
  CharacterCreation/Class-Specific Documentation/Engineer Processes.txt
Labels: Greenlit - Awaiting Review

#626 Constructor Drone Second Trait
  CharacterCreation/01_02_Species_ECSC_Security_Drone.txt
Labels: Greenlit - Awaiting Update

#661 added awareness stat for hunter dog
  CharacterCreation/Class-Specific Documentation/Hunters_Dog.txt
Labels: Greenlit - Awaiting Review
