Repository bleehu/Compound_X, pull requests merged in 2018-09, with the labels that each got.

#628 Added Flechette Shells
  Items/04_00_WeaponAttachments.txt
Labels: Feature Request, Greenlit - Awaiting Update, Priority - Med

#668 Mh/issue 564/medic pass
  CharacterCreation/02_Classes.txt
  CharacterCreation/Class-Specific Documentation/Doctor Procedure Tree - Malpractice.png
Labels: Greenlit - Awaiting Review

#664 Mh/version bump/0.1.6 to r c
  01_01_Basic_Rules.txt
  01_02_Combat_Rules.txt
  01_04_Damage_Types_and_Armor_Types.txt
  01_06_Leveling_Up.txt
  02_01_Advanced_Movement:_Microgravity.txt
  03_Glossary_of_Terms.txt
  CharacterCreation/00_New_Player_Walkthrough.txt
  CharacterCreation/01_Species.txt
  CharacterCreation/02_Classes.txt
  CharacterCreation/03_Feats.txt
  CharacterCreation/06_Skills.txt
  CharacterCreation/Class-Specific Documentation/Doctor Procedures.txt
  CharacterCreation/Class-Specific Documentation/Engineer Processes.txt
  CharacterCreation/Class-Specific Documentation/Hunters_Dog.txt
  CharacterCreation/Class-Specific Documentation/Tome of Spells.txt
  CharacterCreation/README.txt
  CharacterCreation/Readme.md
  Items/04_00_WeaponAttachments.txt
  Items/04_01_Melee_&_Thrown_Weapons.txt
  Items/04_02_Pistols.txt
  Items/04_03_SMGs_&_Shotguns.txt
  Items/04_04_Carbines_AssaultRifles_&_BattleRifles.txt
  Items/04_05_Long_Rifles_&_DMRs.txt
  Items/04_06_MachineGuns_HeavyWeps_&_RocketLaunchers.txt
  Items/05_Armors.txt
  Items/07_Items.txt
  README.md
Labels: Greenlit - Awaiting Review, Priority - High

#677 Mh/version bump/0.1.6 to r c
  01_01_Basic_Rules.txt
  01_02_Combat_Rules.txt
  01_04_Damage_Types_and_Armor_Types.txt
  03_Glossary_of_Terms.txt
  CharacterCreation/01_Species.txt
  CharacterCreation/02_Classes.txt
  CharacterCreation/03_Feats.txt
  CharacterCreation/06_Skills.txt
  CharacterCreation/Class-Specific Documentation/Engineer Processes.txt
  CharacterCreation/Class-Specific Documentation/Hunters_Dog.txt
  CharacterCreation/Class-Specific Documentation/Tome of Spells.txt
  Items/04_00_WeaponAttachments.txt
  Items/04_01_Melee_&_Thrown_Weapons.txt
  Items/07_Items.txt
  README.md
Labels: Greenlit - Awaiting Review, Priority - High

#690 added entry in the glossary for Encounter
  03_Glossary_of_Terms.txt
Labels: Greenlit - Awaiting Review

#691 With the release of melee 2.1, let's call this a major release!
  README.md
Labels: Greenlit - Awaiting Review

#667 Turtlelord26 #591 melee 2.1 critical clarifications
  01_02_Combat_Rules.txt
Labels: Greenlit - Awaiting Review

#678 Add Thrown Expertise, Update Improv Brawler.
  CharacterCreation/03_Feats.txt
Labels: Greenlit - Awaiting Review

#686 restyled Gunslinger Class Feats
  CharacterCreation/02_Classes.txt
Labels: Greenlit - Awaiting Review

#689 restyled Berserker Class Feats
  CharacterCreation/02_Classes.txt
Labels: Greenlit - Awaiting Review

#688 rewrote Marksman Class Feats
  CharacterCreation/02_Classes.txt
Labels: Greenlit - Awaiting Review

#685 rewrote Hacker Class description and feats
  CharacterCreation/02_Classes.txt
  CharacterCreation/Class-Specific Documentation/Hacker Exploits.txt
Labels: Greenlit - Awaiting Review

#684 restyled Engineer Class Feats.
  CharacterCreation/02_Classes.txt
Labels: Greenlit - Awaiting Review

#663 Mh/version bump/0.1.5 to play
  01_01_Basic_Rules.txt
  02_01_Advanced_Movement:_Microgravity.txt
  CharacterCreation/00_New_Player_Walkthrough.txt
  CharacterCreation/02_Classes.txt
  CharacterCreation/03_Feats.txt
  CharacterCreation/Class-Specific Documentation/Doctor Procedures.txt
  Items/04_01_Melee_&_Thrown_Weapons.txt
  Items/07_Items.txt
  README.md
Labels: Greenlit - Awaiting Review, Priority - High

#682 rewrote Specialist Class Feats
  CharacterCreation/02_Classes.txt
Labels: Greenlit - Awaiting Review

#680 Changed style of Doctor Class Feats
  CharacterCreation/02_Classes.txt
Labels: Greenlit - Awaiting Review

#693 Turtlelord26 #367 improvised melee weapons
  01_02_Combat_Rules.txt
  Items/04_01_Melee_&_Thrown_Weapons.txt
Labels: Greenlit - Awaiting Review

#666 Mh/races push/catchup
  01_01_Basic_Rules.txt
  01_02_Combat_Rules.txt
  01_04_Damage_Types_and_Armor_Types.txt
  01_06_Leveling_Up.txt
  03_Glossary_of_Terms.txt
  CharacterCreation/01_Species.txt
  CharacterCreation/02_Classes.txt
  CharacterCreation/03_Feats.txt
  CharacterCreation/06_Skills.txt
  CharacterCreation/Class-Specific Documentation/Doctor Procedures.txt
  CharacterCreation/Class-Specific Documentation/Engineer Processes.txt
  CharacterCreation/Class-Specific Documentation/Hunters_Dog.txt
  CharacterCreation/README.txt
  CharacterCreation/Readme.md
  Items/04_00_WeaponAttachments.txt
  Items/04_01_Melee_&_Thrown_Weapons.txt
  Items/04_02_Pistols.txt
  Items/04_03_SMGs_&_Shotguns.txt
  Items/04_04_Carbines_AssaultRifles_&_BattleRifles.txt
  Items/04_05_Long_Rifles_&_DMRs.txt
  Items/04_06_MachineGuns_HeavyWeps_&_RocketLaunchers.txt
  Items/05_Armors.txt
  Items/07_Items.txt
  Procedural Dungeon Generator
  README.md
Labels: Greenlit - Awaiting Review

#698 added a how-to doc for making characters
  01_01_Basic_Rules.txt
  CharacterCreation/00_00_Creating_a_character.txt
  CharacterCreation/00_01_New_Player_Tips.txt
Labels: Greenlit - Awaiting Review
