Repository bleehu/Compound_X, pull requests merged in 2018-07, with the labels that each got.

#587 changed description of hunter class
  CharacterCreation/02_Classes.txt
Labels: Greenlit - Awaiting Review

#588 Mh/hunter dog/class feats
  CharacterCreation/02_Classes.txt
Labels: Greenlit - Awaiting Pull Request

#590 Clarify use of Repair/Medkits to Stabilize
  01_02_Combat_Rules.txt
Labels: Greenlit - Awaiting Review

#592 Critical skill checks
  01_01_Basic_Rules.txt
Labels: Greenlit - Awaiting Review

#574 Update grenade damage types to current usage
  Items/04_01_Melee_&_Thrown_Weapons.txt
Labels: Greenlit - Awaiting Review

#586 added dog collar/leash
  Items/07_Items.txt
Labels: Greenlit - Awaiting Review

#585 added dog toy item
  Items/07_Items.txt
Labels: Greenlit - Awaiting Review

#603 Added definition of "rounds" and "turns"
  03_Glossary_of_Terms.txt
  CharacterCreation/02_Classes.txt
  CharacterCreation/Class-Specific Documentation/Doctor Procedures.txt
  CharacterCreation/Class-Specific Documentation/Engineer Processes.txt
  Items/04_00_WeaponAttachments.txt
  Items/04_01_Melee_&_Thrown_Weapons.txt
Labels: Greenlit - Awaiting Review, Gripe

#614 Mh/issue 578/gun rule item doc
  01_02_Combat_Rules.txt
  Items/04_02_Pistols.txt
  Items/04_03_SMGs_&_Shotguns.txt
  Items/04_04_Carbines_AssaultRifles_&_BattleRifles.txt
  Items/04_05_Long_Rifles_&_DMRs.txt
  Items/04_06_MachineGuns_HeavyWeps_&_RocketLaunchers.txt
Labels: Greenlit - Awaiting Review

#604 added notes on dual wielding melee weapons
  CharacterCreation/03_Feats.txt
Labels: Greenlit - Awaiting Review

#616 bumped version to 0.1.5
  README.md
Labels: Greenlit - Awaiting Review

#618 Bump R_C to Version 0.1.5
  01_01_Basic_Rules.txt
  01_02_Combat_Rules.txt
  01_06_Leveling_Up.txt
  03_Glossary_of_Terms.txt
  CharacterCreation/02_Classes.txt
  CharacterCreation/03_Feats.txt
  CharacterCreation/06_Skills.txt
  CharacterCreation/Class-Specific Documentation/Doctor Procedures.txt
  CharacterCreation/Class-Specific Documentation/Engineer Processes.txt
  Items/04_00_WeaponAttachments.txt
  Items/04_01_Melee_&_Thrown_Weapons.txt
  Items/04_02_Pistols.txt
  Items/04_03_SMGs_&_Shotguns.txt
  Items/04_04_Carbines_AssaultRifles_&_BattleRifles.txt
  Items/04_05_Long_Rifles_&_DMRs.txt
  Items/04_06_MachineGuns_HeavyWeps_&_RocketLaunchers.txt
  Items/07_Items.txt
  README.md
Labels: Greenlit - Awaiting Review
