Repository bleehu/Compound_X, pull requests merged in 2019-05, with the labels that each got.

#859 Mh/play playable/combat rules
  01_02_Combat_Rules.txt
  Combat Rules/1_Combat_Rules.txt
  Combat Rules/2_Shooting.txt
  Combat Rules/3_Melee_Combat.txt
  Combat Rules/4_Armor_Rules.txt
  Combat Rules/5_Clearing_Rooms.txt
Labels: Greenlit - Awaiting Review

#861 Add Drone Overview Blurb
  CharacterCreation/01_00_Species_Overview.txt
Labels: Greenlit - Awaiting Review

#863 Add condition save rate limit
  Combat Rules/1_Combat_Rules.txt
Labels: Greenlit - Awaiting Review

#862 Expand Subspecies blurb
  CharacterCreation/00_00_Creating_a_character.txt
Labels: Greenlit - Awaiting Review

#860 Added Adrenaline Syringe
  Items/07_Items.txt
Labels: Yellowlit - Awaiting Approval

#857 nerfed Steady Shot
  CharacterCreation/03_Feats.txt
Labels: Greenlit - Awaiting Review

#866 Reorder damage types.
  01_04_Damage_Types_and_Armor_Types.txt
Labels: Greenlit - Awaiting Review

#519 Races-Push
  CharacterCreation/00_00_Creating_a_character.txt
  CharacterCreation/01_00_Species_Overview.txt
  CharacterCreation/01_01_Species_Human.txt
  CharacterCreation/01_02_Species_ECSC_Security_Drone.txt
  CharacterCreation/01_03_Species_Tundari.txt
  CharacterCreation/01_Species.txt
  CharacterCreation/03_Feats.txt
Labels: Blocked, Help Wanted
