Repository bleehu/Compound_X, pull requests merged in 2019-02, with the labels that each got.

#798 added .txt file extension to species overview and added species blurb
  CharacterCreation/01_00_Species_Overview
  CharacterCreation/01_00_Species_Overview.txt
Labels: Greenlit - Awaiting Pull Request

#808 Unconscious condition
  01_02_Combat_Rules.txt
  01_05_Conditions.txt
Labels: Feature Request, Greenlit - Awaiting Review

#804 Nanite removal superbranch -> dev
  01_01_Basic_Rules.txt
  01_06_Leveling_Up.txt
  01_07_Cloaking_Rules.txt
  CharacterCreation/02_Classes.txt
  CharacterCreation/03_Feats.txt
  CharacterCreation/Class-Specific Documentation/Doctor Procedures.txt
  CharacterCreation/Class-Specific Documentation/Engineer Processes.txt
  Items/05_01_Hard_Point_Equipment.txt
  Items/05_Armors.txt
  Items/07_Items.txt
Labels: Greenlit - Awaiting Review

#812 Class Skill Point Clarity
  CharacterCreation/02_Classes.txt
Labels: Greenlit - Awaiting Review, Gripe

#813 Nanite Rework Feat Updates
  CharacterCreation/03_Feats.txt
Labels: Greenlit - Awaiting Review

#814 Reintroduce Duck, Bob, and Weave
  CharacterCreation/03_Feats.txt
Labels: Greenlit - Awaiting Review

#799 added main blurb to opalite doc
  CharacterCreation/01_04_Species_Opaleites.txt
Labels: Greenlit - Awaiting Review

#815 promoted RoseB and Shrub
  README.md
Labels: Greenlit - Awaiting Review

#817 bumped dev version number to 0.2.3
  README.md
Labels: Greenlit - Awaiting Review

#811 Updated Opalites
  CharacterCreation/01_04_Species_Opaleites.txt
Labels: Greenlit - Awaiting Review
