Repository bleehu/Compound_X, pull requests merged in 2019-08, with the labels that each got.

#914 Power reduction on Engineering-minded trait
  CharacterCreation/01_02_Species_ECSC_Security_Drone.txt
Labels: Greenlit - Awaiting Review

#911 Rework of Light Dance
  CharacterCreation/01_04_Species_Opaleites.txt
Labels: Greenlit - Awaiting Review

#915 Reduce complexity on trait I Smell Blood
  CharacterCreation/01_04_Species_Opaleites.txt
Labels: Greenlit - Awaiting Review

#882 Mh/3.0fixes/d filter
  CharacterCreation/01_02_Species_ECSC_Security_Drone.txt
Labels: Greenlit - Awaiting Review

#904 Removed Stat Gains From Opaleite Subspecies
  CharacterCreation/01_04_Species_Opaleites.txt
Labels: Greenlit - Awaiting Review

#917 V 0.3.0 Fixes Prior to RC Ship
  CharacterCreation/01_01_Species_Human.txt
  CharacterCreation/01_02_Species_ECSC_Security_Drone.txt
  CharacterCreation/01_03_Species_Tundari.txt
  CharacterCreation/01_04_Species_Opaleites.txt
Labels: Greenlit - Awaiting Review

#922 added blind condition
  01_05_Conditions.txt
Labels: Greenlit - Awaiting Review

#919 added artistic backgrounds
  CharacterCreation/04_Backgrounds.txt
Labels: Greenlit - Awaiting Review

#916 added some prose for space backgrounds
  CharacterCreation/04_Backgrounds.txt
Labels: Greenlit - Awaiting Review

#918 added trade backgrounds
  CharacterCreation/04_Backgrounds.txt
Labels: Greenlit - Awaiting Review

#920 added just a little more prose to backgrounds and formatted.
  CharacterCreation/04_Backgrounds.txt
Labels: Greenlit - Awaiting Review

#912 Skill Templating Typography in Cryo Drone
  CharacterCreation/01_02_Species_ECSC_Security_Drone.txt
Labels: Greenlit - Awaiting Review

#925 Clarify wording on underbarrel chainsaw
  Items/04_00_WeaponAttachments.txt
Labels: Gripe

#928 Delete Getting Shot section
  Combat Rules/1_Combat_Rules.txt
Labels: Greenlit - Awaiting Review

#934 added description for terran colony background
  CharacterCreation/04_Backgrounds.txt
Labels: Greenlit - Awaiting Update

#936 Turtlelord26 GravTech Updates!
  CharacterCreation/02_Classes.txt
  CharacterCreation/Class-Specific Documentation/Gravity_Technician_Abilities.txt
  Items/04_07_Technician_Equipment
Labels: Greenlit - Awaiting Review
