Repository bleehu/Compound_X, pull requests merged in 2019-09, with the labels that each got.

#937 how did we not have lockpicks yet?
  Items/07_Items.txt
Labels: Greenlit - Awaiting Review

#942 fixed backstab working for ranged attacks
  CharacterCreation/03_Feats.txt
Labels: Greenlit - Awaiting Review

#940 Turtlelord26 species stat points patch
  CharacterCreation/01_01_Species_Human.txt
  CharacterCreation/01_02_Species_ECSC_Security_Drone.txt
Labels: Greenlit - Awaiting Review

#949 renamed "Secondary Stats" to "Capabilities" to clarify wording
  01_01_Basic_Rules.txt
  03_Glossary_of_Terms.txt
  CharacterCreation/00_00_Creating_a_character.txt
  Items/05_Armors.txt
Labels: Greenlit - Awaiting Review

#935 Clothes and Tools
  CharacterCreation/04_Backgrounds.txt
Labels: Greenlit - Awaiting Review, Greenlit - Awaiting Update

#947 changed outdated rules reference
  01_01_Basic_Rules.txt
Labels: Greenlit - Awaiting Review

#950 added stat modifier table
  CharacterCreation/00_00_Creating_a_character.txt
Labels: Greenlit - Awaiting Review

#954 Reword Muscle Memory
  CharacterCreation/03_Feats.txt
Labels: Greenlit - Awaiting Review

#956 Assassin now ORs Weapons Melee/Thrown
  CharacterCreation/02_Classes.txt
Labels: Greenlit - Awaiting Review

#960 Clarity on miss chance limits
  Combat Rules/2_Shooting.txt
Labels: Greenlit - Awaiting Review

#961 removed dumb level 0 idea
  CharacterCreation/02_Classes.txt
Labels: Greenlit - Awaiting Review, Gripe

#941 Reveraine fixing tundari spelling
  CharacterCreation/01_00_Species_Overview.txt
  CharacterCreation/01_03_Species_Tundari.txt
Labels: Greenlit - Awaiting Review

#946 added below the belt feat
  CharacterCreation/03_Feats.txt
Labels: Greenlit - Awaiting Review

#945 added laser dampening manifold attachment
  Items/04_00_WeaponAttachments.txt
Labels: Greenlit - Awaiting Review
