Repository bleehu/Compound_X, pull requests merged in 2019-03, with the labels that each got.

#818 Ship medical nanites to R_C
  01_01_Basic_Rules.txt
  01_02_Combat_Rules.txt
  01_04_Damage_Types_and_Armor_Types.txt
  01_05_Conditions.txt
  01_06_Leveling_Up.txt
  01_07_Cloaking_Rules.txt
  CharacterCreation/02_Classes.txt
  CharacterCreation/03_Feats.txt
  CharacterCreation/Class-Specific Documentation/Doctor Procedures.txt
  CharacterCreation/Class-Specific Documentation/Engineer Processes.txt
  Items/04_01_Melee_&_Thrown_Weapons.txt
  Items/05_01_Hard_Point_Equipment.txt
  Items/05_Armors.txt
  Items/07_Items.txt
  README.md
Labels: Blocked, Greenlit - Awaiting Review

#819 Add numbers to the Sang'mau Powerful trait
  CharacterCreation/01_03_Species_Tundari.txt
Labels: Greenlit - Awaiting Review

#825 moved grenades to their own file
  Items/04_01_Melee_&_Thrown_Weapons.txt
  Items/06_Explosives.txt
Labels: Greenlit - Awaiting Review

#822 added rules on buying and selling.
  01_01_Basic_Rules.txt
Labels: Greenlit - Awaiting Review

#826 Add mechanics to Tundari Clawed trait
  CharacterCreation/01_03_Species_Tundari.txt
Labels: Greenlit - Awaiting Review

#827 added movment reduction for security drone armor species trait
  CharacterCreation/01_02_Species_ECSC_Security_Drone.txt
Labels: Greenlit - Awaiting Review

#829 Delete Monk Feat
  CharacterCreation/03_Feats.txt
Labels: Greenlit - Awaiting Review

#828 Add Miss Chance to Improvised Weapons for Throwing
  01_02_Combat_Rules.txt
  Items/04_01_Melee_&_Thrown_Weapons.txt
Labels: Bug, Greenlit - Awaiting Review

#831 Delete vestigial thrown weapon rules text
  01_02_Combat_Rules.txt
Labels: Greenlit - Awaiting Review

#832 Minor rework of Twitch feat
  CharacterCreation/03_Feats.txt
Labels: Gripe
